### ISSUE TITLE
Custom URL Scheme

### ISSUE THREAD

**Issue by Rufus31415** [mozilla-mobile/webxr-ios-js#108]
Would it be possible to implement a custom url scheme, like wxrv:// which was present in the first version.

**Comment by sael-you** [comment]
@blairmacintyre any update please ? apparently it's still not working, and the new protocol "xrviewer" doesn't seem to redirect to the url

**Comment by blairmacintyre** [comment]
Mozilla shut down the Mixed Reality team almost a year ago, I am not working on this anymore.

**Comment by sael-you** [comment]
Thanks a lot, anyway if anyone is still interested in WebXR viewer url scheme here it is "xrviewer://open-url/?url=https://.........."
