### ISSUE TITLE
Mime-type for USDZ isn't correct and results in incorrect behaviour when trying to use QuickLook

### ISSUE THREAD

**Issue by hybridherbst** [mozilla-mobile/webxr-ios-js#109]
To reproduce:

- Open https://modelviewer.dev/examples/augmented-reality.html
- Select ... menu and "Request Mobile Site"
- Click the little AR button

**Expected:** Apple's Quick Look opens with the USDZ file
**Actual:** Firefox downloads the USDZ file

Quick Look is picky about the mime type which is probably incorrect here.

**Comment by blairmacintyre** [comment]
I don't think Quick Look works with anything except Safari (or the embeddeble SFSafariWebView).  So it won't work in 3rd party browsers (Chrome, Firefox, WebXRViewer).

**Comment by hybridherbst** [comment]
Well, sorry, but instead of guessing you could have checked, and would have seen that this is indeed supported in Chrome on iOS – just try the above example.
I personally reported it as a bug that it wasn't working (they also had the wrong mime type, for .usdz and also for .reality) some months ago and they fixed it.

Please reopen.

**Comment by blairmacintyre** [comment]
I didn't guess, I looked at the docs, which implied  it only works in SFSafariWebView.   (I don't use Chrome, so I don't have it installed to check, I shouldn't have included that in my list.  The behavior you describe also happens in Firefox.)

We'll leave it open, but it needs to be fixed in Firefox for iOS, not in this polyfill.  Perhaps file an issue there.

**Comment by hybridherbst** [comment]
For reference,
new issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1652011
old issue marked as fixed but still not working: https://bugzilla.mozilla.org/show_bug.cgi?id=1528147

**Comment by blairmacintyre** [comment]
Interesting, so it's a regression.  Thanks for noticing.
