### ISSUE TITLE
Debugging a webXR experience that displays blackout 

### ISSUE THREAD

**Issue by FuzzyWobble** [mozilla-mobile/webxr-ios-js#111]
Hello, I created a [webXR dance experience](https://www.instagram.com/p/CEVZxCOjHFt/?utm_source=ig_web_copy_link) that is working fine on Android. 

When I load in webXR Viewer it just displays a black screen. 

You can try it at [https://pararty.com/](https://pararty.com/)

1. What's a good way to debug this?

2. Is there a way to detect webxr-viewer browser with JS? 

Thanks.

**Comment by FuzzyWobble** [comment]
*bump*

**Comment by philip-lamb** [comment]
https://uploadvr.com/mozilla-layoffs-vr-ar/
