### ISSUE TITLE
Hosted version of `webxr-2.0.js` seems to be down, breaking Mozilla XR Viewer

### ISSUE THREAD

**Issue by hybridherbst** [mozilla-mobile/webxr-ios-js#125]
So, despite being a couple years old, a number of people still use Mozilla's XR Viewer app to view WebXR experiences on iOS.

However, seems since recently, this URL doesn't exist anymore:
[webxr-ios.webxrexperiments.com/dist/webxr-2.0.js](https://webxr-ios.webxrexperiments.com/dist/webxr-2.0.js)

It's fetched by the browser when launching XR experiences. So currently, those don't work at all anymore, rendering XR Viewer's XR mode inoperable.

@takahirox @blairmacintyre do you maybe know who I could reach out to to ideally just restore that URL?

**Comment by blairmacintyre** [comment]
I'm poking around to see if I can get this fixed.  I don't know many people at Mozilla right now, though.

**Comment by hybridherbst** [comment]
Thanks so much, fingers crossed 🤞

**Comment by blairmacintyre** [comment]
Ok, give it a go.  I think it's working again.

**Comment by hybridherbst** [comment]
It is! Thank you so much 💚
